function listarItens(chave) {
  if (chave === 'sobreProjeto') {
    return [
      {
        descricao: "O grupo de pesquisa MIND (Movimento para Inclusão e Neurodiversidade) surgiu da necessidade de compartilhar e divulgar a temática da Educação Inclusiva em 2021, mas sendo feito o processo de certificação na CNPQ, como grupo de pesquisa em 27/05/2025. Assim, o grupo tem como propósito promover conhecimentos, práticas e pesquisas que favoreçam a inclusão de todos os estudantes nos espaços escolares, principalmente os Neurodivergentes. A inclusão escolar de alunos com Transtorno do Espectro Autista (TEA) só se concretiza plenamente quando há compromisso institucional, formação adequada, valorização da diversidade e parcerias efetivas entre escola, família e políticas públicas. Ir além do adaptar conteúdos e mudanças curriculares, é necessário transformar mentalidades, promover um acolhimento genuíno e garantir que cada aluno seja reconhecido e respeitado em sua singularidade. O processo de inclusão de alunos com TEA requer práticas pedagógicas planejadas, sensíveis e contextualizadas. Ensinar na perspectiva inclusiva implica não apenas garantir o acesso físico à escola, mas também assegurar a participação ativa, o sentimento de pertencimento e o pleno desenvolvimento do aluno no ambiente escolar. A construção dessa inclusão parte de uma compreensão ampla do aluno com TEA, considerando seus modos de comunicação e aprendizagem. Isso exige, ainda, uma transformação nas estruturas escolares, com o envolvimento ativo de toda a comunidade educativa, especialmente das famílias. O papel do professor/docente/educador vai além de transmissor de conhecimento específicos, começa a ser construído já na sua formação inicial, tendo seguimento na formação continuada e na prática educacional.",     
	principaisestrategias: "Estratégias eficazes são as que se baseiam no conhecimento profundo do aluno e seu contexto; Adaptação curricular individualizada; Ambientes afetivos e seguros; Uso de materiais visuais e concretos; Comunicação clara e estruturada; Transformar os conteúdos escolares de forma a garantir a participação e a aprendizagem reais, com exemplificação de situações do cotidiano; Proporcionar ao aluno previsibilidade nas rotinas; Desenvolvimento de linguagem, habilidades sociais e flexibilidade cognitiva; Práticas pedagógicas colaborativas e criativas; Formação continuada dos educadores; Parceria contínua com as famílias, docentes e profissionais por meio de oficinas e reuniões.",
	desafios: "Alguns dos grandes desafios envolvem a falta de formação específica de professores; Práticas normativas que excluem; Cobrança excessiva e sem apoio pedagógico; Falta de articulação entre os setores escolares e professores; Persistência de preconceito, estigmas e bullying; Em muitas situações, a inclusão ainda depende de ações isoladas ou da boa vontade de porfessores/profissionais.",
	perspectivas: "Entender como os professores vivenciam o processo de inclusão dos alunos com TEA em sala de aula, como sentem, pensam e atribuem significado a essa experiência, quais necessidades e adaptações curriculares educacionais são necessárias, a partir do seu ponto de vista e das necessidades individualizadas dos alunos com TEA.",
	certificacao: "http://dgp.cnpq.br/dgp/espelhogrupo/6627435564246794"
},

    ];
  }
  return [];
}
