function listarItens(tipo) {
  if (tipo === 'autores') {
    return [

      //atenção: se faltar algum campo não irá listar os dados, a ordem aqui não implica, só nome das variáveis
      {
        id: "1",
        status: "Ativo",
        nome: "Alexssandro Ferreira da Silva",
        formacao: "Possui Técnico em Informática, Graduação em Administração, Tecnólogo em Análise e Desenvolvimento de Sistemas, Cursando Pedagogia, Cursando Mestrado em Educação pelo PECIM - Unicamp-SP, atualmente é lotado no IFSP Campus Jacareí como Técnico de Tenologia da Informação",
        titulo: "Mestrando",
        tipoParticipacao: "Colaborador Interno",
        anoIngresso: "2022",
        anoSaida: "Atualmente",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/3843853231671192",
        imagem: "alexssandro.jpg",  // <-- Só o nome do arquivo
      }, 
      {
        id: "2",
        status: "Ativo",
        nome: "Ana Clara Machado Godinho",
        formacao: "Atualmente está cursando o Ensino Médio Integrado em Informática no IFSP Campus Jacareí",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2025",
        anoSaida: "Atualmente",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/8868488747354907",
        imagem: "ana_clara_godinho.jpg",  // <-- Só o nome do arquivo
      }, 
      {
        id: "3",
        nome: "Ana Paula Kawabe de Lima Ferreira",
        status: "Ativo",
        formacao: "Possui Licenciatura Plena em Química pelo Instituto de Química de Araraquara-UNESP e Mestrado em Ciências pela Universidade Federal de Lavras, Cursando Pedagogia, Cursando Doutorado em Educação pelo PECIM - Unicamp-SP, atualmente é lotada no IFSP Campus Jacareí como professora de Química",
        titulo: "Mestrado",
        tipoParticipacao: "Coordenação",
        anoIngresso: "2021",
        anoSaida: "Atualmente",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/4564160743198905",
        imagem: "ana_kawabe.jpg",  // <-- Só o nome do arquivo
      },
      {
        id: "4",
        nome: "Bianca Estrela Montemor Abdalla França Camargo",
        status: "Ativo",
        formacao: "Atualmente está cursando Psicologia Universidade Federal de São João Del Rei (UFSJ-MG)",
        titulo: "Estudante de Ensino Superior",
        tipoParticipacao: "Colaborador Externo",
        anoIngresso: "2025",
        anoSaida: "Atualmente",
        instituicao: "UFSJ-MG",
        lattes: "http://lattes.cnpq.br/4013441577274463",
        imagem: "bianca_motemor.jpg",  // <-- Só o nome do arquivo
      },
      {
        id: "5",
        nome: "Eduardo Moreno Sanches Junior",
        status: "Ativo",
        formacao: "Atualmente está cursando o Ensino Médio Integrado em Informática no IFSP Campus Jacareí",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2025",
        anoSaida: "Atualmente",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/9599629648933536",
        imagem: "eduardo_moreno.jpg",  // <-- Só o nome do arquivo
      },
    {
        id: "6",
        nome: "Gabriel de Paula Baroni",
        status: "Ativo",
        formacao: "Atualmente está cursando o Ensino Médio Integrado em Informática no IFSP Campus Jacareí",
        titulo: "Ensino Médio",
        tipoParticipacao: "Colaborador Interno e Bolsista de outro Coordenador (prof. Tardelli Stekel - Informática)",
        anoIngresso: "2024",
        anoSaida: "Atualmente",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/0153768116859752",
        imagem: "gabriel_baroni.jpg",  // <-- Só o nome do arquivo
      },
      {
        id: "7",
        nome: "Ivana Elena Camejo Aviles",
        status: "Ativo",
        formacao: "Possui Licenciatura em Biologia, atualmente é lotada no DBFE do Instituto de Biologia da UNICAMP, credenciada no Programa de Pós-Graduação Multiunidades em Ensino de Ciências e Matemática, PECIM e no Programa de Mestrado Profissional em Ensino de Biologia em Rede Nacional, PROFBIO. Pesquisadora do Laboratório de Tecnologia Educacional, LTE do Instituto de Biologia da UNICAMP",
        titulo: "Doutorado",
        tipoParticipacao: "Colaborador Externo",
        anoIngresso: "2024",
        anoSaida: "Atualmente",
        instituicao: "Unicamp Campinas",
        lattes: "http://lattes.cnpq.br/0294329481051613",
        imagem: "ivana_camejo.jpg",  // <-- Só o nome do arquivo
      },
       {
        id: "8",
        nome: "Mateus Cayque Figueiredo Gomes",
        status: "Ativo",
        formacao: "Atualmente está cursando Biologia na Unesp",
        titulo: "Estudante de Ensino Superior",
        tipoParticipacao: "Colaborador Externo",
        anoIngresso: "2025",
        anoSaida: "Atualmente",
        instituicao: "Unicamp Campinas",
        lattes: "http://lattes.cnpq.br/1327427239923152",
        imagem: "mateus_cayque.jpg",  // <-- Só o nome do arquivo
      },
      {
        id: "9",
        status: "Ativo",
        nome: "Ricardo Henrique dos Reis Nascimento",
        formacao: "Autalmente está cursando Ciências da Computação na Universidade Federal de São Paulo (UNIFESP - Campus de São José dos Campos/SP)",
        titulo: "Estudante de Ensino Superior",
        tipoParticipacao: "Colaborador Externo",
        anoIngresso: "2025",
        anoSaida: "Atualmente",
        instituicao: "UNIFESP",
        lattes: "http://lattes.cnpq.br/9908620895084723",
        imagem: "ricardo_henrique.jpg",  // <-- Só o nome do arquivo
      },
     {     
        id: "10",
        status: "Ativo",
        nome: "Tardelli Ronan Coelho Stekel",
        formacao: "Graduação em Engenharia Elétrica pela Universidade Federal de Santa Maria (UFSM), Mestrado em Geofísica Espacial pelo Instituto Nacional de Pesquisas Espaciais (INPE), com mestrado sanduíche FAPESP na George Mason University (GMU), Fairfax, VA e no Naval Research Laboratory (NRL), Washington, D.C. Doutor em Geofísica Espacial pelo INPE e doutorado sanduíche no Max-Planck-Institut für Sonnensystemforschung (MPS) em Göttingen, Alemanha, atulmente é lotado no IFSP Campus Jacareí como professor de Informática",
        titulo: "Doutorado",
        tipoParticipacao: "Colaborador Interno",
        anoIngresso: "2024",
        anoSaida: "Atualmente",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/4733654913237092",
        imagem: "tardelli.jpg",  // <-- Só o nome do arquivo / se estiver sem foto no lattes adota foto default
      },
    {     
        id: "11",
        status: "Ativo",
        nome: "Thiago Marinho Santos",
        formacao: "Atualmente está cursando o Ensino Médio Integrado em Administração no IFSP Campus Jacareí",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2025",
        anoSaida: "Atualmente",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/7416672377207564",
        imagem: "thiago_marinho.jpg",  // <-- Só o nome do arquivo
      },
    {     
        id: "12",
        status: "Ativo",
        nome: "Yara Vitoria Claro de Freitas",
        formacao: "Atualmente está cursando o Ensino Médio Integrado em Informática no IFSP Campus Jacareí",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2025",
        anoSaida: "Atualmente",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/6862799595515603",
        imagem: "yara_vitoria.jpg",  // <-- Só o nome do arquivo
      },

      
      {     
        id: "13",
        status: "Inativo",
        nome: "Bianca Estrela Montemor Abdalla França Camargo",
        formacao: "Cursando Ensino Médio Integrado em Informática",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2022",
        anoSaida: "2023",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/4013441577274463",
        imagem: "bianca_motemor.jpg",  // <-- Só o nome do arquivo
      },
      {  
        id: "14",
        nome: "Gabriel Kawabe de Lima Ferreira",
        status: "Inativo",
        formacao: "Cursando Ensino Fundamental",
        titulo: "Ensino Fundamental",
        tipoParticipacao: "Colaborador Externo",
        anoIngresso: "2023",
        anoSaida: "2024",
        instituicao: "Escola Anglo Jacareí",
        lattes: "http://lattes.cnpq.br/2050192695648588",
        imagem: "gabriel_kawabe.jpg",  // <-- Só o nome do arquivo
      },
      {     
        id: "15",
        status: "Inativo",
        nome: "Lucas Caraça dos Santos",
        formacao: "Cursando Ensino Médio Integrado em Informática",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2023",
        anoSaida: "2024",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/4392658666289947",
        imagem: "lucas_caraca.jpg",  // <-- Só o nome do arquivo
      },
      {     
        id: "16",
        status: "Inativo",
        nome: "Luis Gustavo Cardoso",
        formacao: "Cursando Ensino Médio Integrado em Administração",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2024",
        anoSaida: "2024",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/8529767440328069",
        imagem: "luis_cardoso.jpg",  // <-- Só o nome do arquivo
      },
      {     
        id: "17",
        status: "Inativo",
        nome: "Lyan Lisboa de Souza",
        formacao: "Cursando Ensino Médio Integrado em Informática",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2023",
        anoSaida: "2023",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/2246705450772654",
        imagem: "lyan_lisboa.jpg",  // <-- Só o nome do arquivo
      },
      {     
        id: "18",
        status: "Inativo",
        nome: "Maria Wianney Miranda Almeida",
        formacao: "Cursando Ensino Médio Integrado em Informática",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2022",
        anoSaida: "2023",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/3933685986001878",
        imagem: "maria_wianney.jpg",  // <-- Só o nome do arquivo
      },
      {     
        id: "19",
        status: "Inativo",
        nome: "Mateus Cayque Figueiredo Gomes",
        formacao: "Cursando Ensino Médio Integrado em Administração",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2024",
        anoSaida: "2024",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/1327427239923152",
        imagem: "mateus_cayque.jpg",  // <-- Só o nome do arquivo
      },
      {
        id: "20",
        status: "Inativo",
        nome: "Ricardo Henrique dos Reis Nascimento",
        formacao: "Cursando Ensino Médio Integrado em Informática",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2022",
        anoSaida: "2023",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/9908620895084723",
        imagem: "ricardo_henrique.jpg",  // <-- Só o nome do arquivo
      },
      {
        id: "21",
        status: "Inativo",
        nome: "Ryan Cristian Sousa Campos",
        formacao: "Cursando Ensino Médio Integrado em Informática",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2023",
        anoSaida: "2023",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/5159854768377627",
        imagem: "ryan_cristian.jpg",  // <-- Só o nome do arquivo
      },
       {
        id: "22",
        status: "Ativo",
        nome: "Luis Guilherme dos Reis Nascimento",
        formacao: "Atualmente está cursando o Ensino Médio Integrado em Informática no IFSP Campus Jacareí",
        titulo: "Ensino Médio",
        tipoParticipacao: "Voluntário Interno",
        anoIngresso: "2025",
        anoSaida: "",
        instituicao: "IFSP Jacareí",
        lattes: "https://lattes.cnpq.br/2838359900736717",
        imagem: "luis_reis.jpg",  // <-- Só o nome do arquivo
      },
    ];
  }
  return [];
}
