function listarItens(tipo) {
  if (tipo === 'autores') {
    return [

      //atenção: se faltar algum campo não irá listar os dados, a ordem aqui não implica, só nome das variáveis
      {
        id: "1",
        status: "Ativo",
        nome: "Alexssandro Ferreira da Silva",
        formacao: "Atualmente atua no IFSP Campus de Jacareí no cargo de Técnico de Tecnologia da Informação no setor da CAE (Coordenadoria de Apoio ao Ensino). Cursando Licenciatura em Pedagogia (EAD) pela Univesp. Cursos concluídos: Mestrado em Ensino de Ciências e Matemática pela Unicamp de Campinas-SP (03/2026), Tecnólogo em Análise e Desenvolvimento de Sistemas - IFSP de Jacareí (03/2024); Pós Graduação: Educação Empreendedora pela (03/2017 a 09/2019) - Polo de Santa Isabel/SP e Gestão Pública Municipal (03/2017 a 09/2019) - Polo de Monte Sião/MG, ambas pela UFSJ/MG; Especialização em Atendimento Educacional Especializado (10/2025 a 04/2026) e Transtornos Específicos da Aprendizagem e do Neurodesenvolvimento (06/2025 a 12/2026) ambas pela FESP - Faculdade de Educação Superior do Paraná (12/2025); Técnico em Informática (2012-2014) - Polo Pouso Alegre/MG pelo campus do IFSULDEMINAS. Graduação em Administração de Empresas - FADMINAS (2003-2007). Atuação Pesquisa: colaborador em projetos de Pesquisa, Ensino e Extensão usando CAA (Comunicação Aumentativa e Alternativa) e Scratch para alunos com inclusão de alunos com TEA (Transtorno do Espectro Autista).",
        titulo: "Mestrando",
        tipoParticipacao: "Colaborador Interno",
        anoIngresso: "2022",
        anoSaida: "Atualmente",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/3843853231671192",
        imagem: "alexssandro.jpg",  // <-- Só o nome do arquivo
      }, 
      {
        id: "2",
        status: "Inativo",
        nome: "Ana Clara Machado Godinho",
        formacao: "Cursou o Ensino Médio Integrado em Informática no IFSP Campus Jacareí",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2025",
        anoSaida: "2025",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/8868488747354907",
        imagem: "ana_clara_godinho.jpg",  // <-- Só o nome do arquivo
      }, 
      {
        id: "3",
        nome: "Ana Paula Kawabe de Lima Ferreira",
        status: "Ativo",
        formacao: "Atualmente é lotada no IFSP Campus Jacareí como professora de Química e é coordenadora do Grupo de Pesquisa MIND (Movimento para Inclusão e Neurodiversidade). Possui Licenciatura Plena em Química pelo Instituto de Química de Araraquara-UNESP e Mestrado em Ciências pela Universidade Federal de Lavras, possui: Especialização em Transtornos Específicos da Aprendizagem e do Neurodesenvolvimento(2025) pela FESP - Faculdade de Educaçao Superior do Paraná; Especialização em Especialização em Educação Especial e Inclusiva (2023 a 2025) pela Universidade Federal do ABC, UFABC. Cursando Pedagogia, Cursando Doutorado em Educação pelo PECIM - Unicamp-SP. Formação complementar: Educação em Direitos Humanos e Diversidades: educar-se e educar para a con. (180h) pela Universidade Federal de Uberlândia - UFU (2024); Manejos Comportamentais ´para individuos com TOD no contexto escolar (125h) pela Faculdade de Ensino Superior Dom Bosco - FDB (2024); AEE: Deficiência física com ênfase na aplicação de recursos de Tecnologia Assistiva (90h) pela Secretaria de Modalidades Especializadas de Educação - SEMESP-AVAMEC (2023); Altas Habilidades ou Superdotação: práticas educação inclusiva no contexto AEE (180h) pela Universidade Federal de Uberlândia - UFU (2022-2023); ECQ 5720 - Mapas Conceituais e Aprendizagem Colaborativa (120h) pela USP - INTERUNIDADES EM ENSINO DE CIÊNCIAS - USP ECQ (2021).",
        titulo: "Mestrado",
        tipoParticipacao: "Coordenação",
        anoIngresso: "2021",
        anoSaida: "Atualmente",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/4564160743198905",
        imagem: "ana_kawabe.jpg",  // <-- Só o nome do arquivo
      },
      {
        id: "4",
        nome: "Bianca Estrela Montemor Abdalla França Camargo",
        status: "Inativo",
        formacao: "Cursando Psicologia na Universidade Federal de São João Del Rei (UFSJ-MG)",
        titulo: "Estudante de Ensino Superior",
        tipoParticipacao: "Colaborador Externo",
        anoIngresso: "2025",
        anoSaida: "2025",
        instituicao: "UFSJ-MG",
        lattes: "http://lattes.cnpq.br/4013441577274463",
        imagem: "bianca_motemor.jpg",  // <-- Só o nome do arquivo
      },
      {
        id: "5",
        nome: "Eduardo Moreno Sanches Junior",
        status: "Ativo",
        formacao: "Atualmente está cursando o Ensino Médio Integrado em Informática no IFSP Campus Jacareí",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2025",
        anoSaida: "Atualmente",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/9599629648933536",
        imagem: "eduardo_moreno.jpg",  // <-- Só o nome do arquivo
      },
    {
        id: "6",
        nome: "Gabriel de Paula Baroni",
        status: "Inativo",
        formacao: "Cursou o Ensino Médio Integrado em Informática no IFSP Campus Jacareí",
        titulo: "Ensino Médio",
        tipoParticipacao: "Colaborador Interno e Bolsista de outro Coordenador (prof. Tardelli Stekel - Informática)",
        anoIngresso: "2024",
        anoSaida: "2025",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/0153768116859752",
        imagem: "gabriel_baroni.jpg",  // <-- Só o nome do arquivo
      },
      
      
       {
        id: "8",
        nome: "Mateus Cayque Figueiredo Gomes",
        status: "Ativo",
        formacao: "Atualmente está cursando Biologia na Unesp",
        titulo: "Estudante de Ensino Superior",
        tipoParticipacao: "Colaborador Externo",
        anoIngresso: "2025",
        anoSaida: "Atualmente",
        instituicao: "Unicamp Campinas",
        lattes: "http://lattes.cnpq.br/1327427239923152",
        imagem: "mateus_cayque.jpg",  // <-- Só o nome do arquivo
      },
      {
        id: "9",
        status: "Ativo",
        nome: "Ricardo Henrique dos Reis Nascimento",
        formacao: "Atualmente está cursando Ciências da Computação na Universidade Federal de São Paulo (UNIFESP - Campus de São José dos Campos/SP)",
        titulo: "Estudante de Ensino Superior",
        tipoParticipacao: "Colaborador Externo",
        anoIngresso: "2025",
        anoSaida: "Atualmente",
        instituicao: "UNIFESP",
        lattes: "http://lattes.cnpq.br/9908620895084723",
        imagem: "ricardo_henrique.jpg",  // <-- Só o nome do arquivo
      },
     {     
        id: "10",
        status: "Ativo",
        nome: "Tardelli Ronan Coelho Stekel",
        formacao: "Possui Graduação em Engenharia Elétrica pela Universidade Federal de Santa Maria (UFSM), Mestrado em Geofísica Espacial pelo Instituto Nacional de Pesquisas Espaciais (INPE), com mestrado sanduíche FAPESP na George Mason University (GMU), Fairfax, VA e no Naval Research Laboratory (NRL), Washington, D.C. Doutor em Geofísica Espacial pelo INPE e doutorado sanduíche no Max-Planck-Institut für Sonnensystemforschung (MPS) em Göttingen, Alemanha, atulmente é lotado no IFSP Campus Jacareí como professor de Informática",
        titulo: "Doutorado",
        tipoParticipacao: "Colaborador Interno",
        anoIngresso: "2024",
        anoSaida: "Atualmente",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/4733654913237092",
        imagem: "tardelli.jpg",  // <-- Só o nome do arquivo / se estiver sem foto no lattes adota foto default
      },
    {     
        id: "11",
        status: "Inativo",
        nome: "Thiago Marinho Santos",
        formacao: "Está cursando o Ensino Médio Integrado em Administração no IFSP Campus Jacareí",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2025",
        anoSaida: "2025",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/7416672377207564",
        imagem: "thiago_marinho.jpg",  // <-- Só o nome do arquivo
      },
    {     
        id: "12",
        status: "Inativo",
        nome: "Yara Vitória Claro de Freitas",
        formacao: "Cursou o Ensino Médio Integrado em Informática no IFSP Campus Jacareí",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2025",
        anoSaida: "2025",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/6862799595515603",
        imagem: "yara_vitoria.jpg",  // <-- Só o nome do arquivo
      },

      
      {     
        id: "13",
        status: "Inativo",
        nome: "Bianca Estrela Montemor Abdalla França Camargo",
        formacao: "Cursou o Ensino Médio Integrado em Informática",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2022",
        anoSaida: "2023",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/4013441577274463",
        imagem: "bianca_motemor.jpg",  // <-- Só o nome do arquivo
      },
      {  
        id: "14",
        nome: "Gabriel Kawabe de Lima Ferreira",
        status: "Inativo",
        formacao: "Cursou Ensino Fundamental",
        titulo: "Ensino Fundamental",
        tipoParticipacao: "Colaborador Externo",
        anoIngresso: "2023",
        anoSaida: "2024",
        instituicao: "Escola Anglo Jacareí",
        lattes: "http://lattes.cnpq.br/2050192695648588",
        imagem: "gabriel_kawabe.jpg",  // <-- Só o nome do arquivo
      },
      {     
        id: "15",
        status: "Inativo",
        nome: "Lucas Caraça dos Santos",
        formacao: "Cursou Ensino Médio Integrado em Informática",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2023",
        anoSaida: "2024",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/4392658666289947",
        imagem: "lucas_caraca.jpg",  // <-- Só o nome do arquivo
      },
      {     
        id: "16",
        status: "Inativo",
        nome: "Luis Gustavo Cardoso",
        formacao: "Cursando Ensino Médio Integrado em Administração",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2024",
        anoSaida: "2024",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/8529767440328069",
        imagem: "luis_cardoso.jpg",  // <-- Só o nome do arquivo
      },
      {     
        id: "17",
        status: "Inativo",
        nome: "Lyan Lisboa de Souza",
        formacao: "Cursou 0oEnsino Médio Integrado em Informática",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2023",
        anoSaida: "2023",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/2246705450772654",
        imagem: "lyan_lisboa.jpg",  // <-- Só o nome do arquivo
      },
      {     
        id: "18",
        status: "Inativo",
        nome: "Maria Wianney Miranda Almeida",
        formacao: "Cursou o Ensino Médio Integrado em Informática",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2022",
        anoSaida: "2023",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/3933685986001878",
        imagem: "maria_wianney.jpg",  // <-- Só o nome do arquivo
      },
      {     
        id: "19",
        status: "Inativo",
        nome: "Mateus Cayque Figueiredo Gomes",
        formacao: "Cursou Ensino Médio Integrado em Administração",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2024",
        anoSaida: "2024",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/1327427239923152",
        imagem: "mateus_cayque.jpg",  // <-- Só o nome do arquivo
      },
      {
        id: "20",
        status: "Inativo",
        nome: "Ricardo Henrique dos Reis Nascimento",
        formacao: "Cursou Ensino Médio Integrado em Informática",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2022",
        anoSaida: "2023",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/9908620895084723",
        imagem: "ricardo_henrique.jpg",  // <-- Só o nome do arquivo
      },
      {
        id: "21",
        status: "Inativo",
        nome: "Ryan Cristian Sousa Campos",
        formacao: "Cursou Ensino Médio Integrado em Informática",
        titulo: "Ensino Médio",
        tipoParticipacao: "Bolsista",
        anoIngresso: "2023",
        anoSaida: "2023",
        instituicao: "IFSP Jacareí",
        lattes: "http://lattes.cnpq.br/5159854768377627",
        imagem: "ryan_cristian.jpg",  // <-- Só o nome do arquivo
      },
       {
        id: "22",
        status: "Ativo",
        nome: "Luis Guilherme dos Reis Nascimento",
        formacao: "Atualmente está cursando o Ensino Médio Integrado em Informática no IFSP Campus Jacareí",
        titulo: "Ensino Médio",
        tipoParticipacao: "Voluntário Interno",
        anoIngresso: "2025",
        anoSaida: "Atualmente",
        instituicao: "IFSP Jacareí",
        lattes: "https://lattes.cnpq.br/2838359900736717",
        imagem: "luis_reis.jpg",  // <-- Só o nome do arquivo
      },
    ];
  }
  return [];
}
